### ISSUE TITLE
What is the signature.js file used for?

### ISSUE THREAD

**Issue by a1300** [sqfasd/asch-js#16]
Dear @liangpeili 

Which purpose has the [signature.js](https://github.com/AschPlatform/asch-js/blob/master/lib/transactions/signature.js) file?

Is it necessary for the ASCH release 1.4.2 or can it be deleted?

Thanks!
All the best
a1300

**Comment by liangpeili** [comment]
It's used in signing the transaction and is necessary. in asch-cli 

```
  var trs = aschJS.signature.createSignature(options.secret, options.secondSecret);
  getApi().broadcastTransaction(trs, function (err, result) {
    console.log(err || result.transactionId)
  });
```
