### ISSUE TITLE
Fix asch-js tests

### ISSUE THREAD

**Issue by a1300** [sqfasd/asch-js#20]
Dear @sqfasd, dear @liangpeili 

I would like to fix the tests for __asch-js__.

Could you assign this issue to me?

All the best
a1300

**Comment by liangpeili** [comment]
Thanks! @a1300

**Comment by a1300** [comment]
Dear @sqfasd , dear @liangpeili 

I have failing tests because of a regression bug.
the `aschJS.crypto.verify(trs)` is not working due to:  
https://github.com/AschPlatform/asch-js/blob/8eec2de954a9ca5c9bda5ba5d7d75db2431b29ae/lib/transactions/crypto.js#L219

It should be:  
```js
var signatureBuffer = new Buffer(transaction.signatures[0], "hex");
```

Can I provide a separate pull request to fix this issue?

All the best
a1300

**Comment by a1300** [comment]
I provided a pull request (https://github.com/AschPlatform/asch-js/pull/23) that fixes the problems with `asch.crypto`

**Comment by a1300** [comment]
Pull request https://github.com/AschPlatform/asch-js/pull/26 closes this issue
